language: node_js

node_js:
  - node
  - lts/*

jobs:
  include:
    - stage: greenkeeper
      node_js: lts/*
      before_install: npm install -g greenkeeper-lockfile
      before_script: greenkeeper-lockfile-update
      script: skip
      after_script: greenkeeper-lockfile-upload

    - stage: test
      after_success:
        - npm run report-coverage

    - stage: verify codestyle
      node_js: lts/*
      script:
        - commitlint-travis
        - standard

    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release

stages:
  - name: verify codestyle
  - name: compile
  - name: test
    if: NOT branch =~ /^greenkeeper\/.*$/
  - name: greenkeeper
    if: branch =~ /^greenkeeper\/.*$/
  - name: release
    if: branch = master
