language: node_js

node_js:
  - node
  - lts/*

jobs:
  include:
    - stage: verify codestyle
      node_js: lts/*
      script:
        - commitlint-travis
        - standard
    - stage: test
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
